server.document-root = "/var/www/html"
server.port = 9090
server.indexfiles = ("index.html")
mimetype.assign = (
    ".html" => "text/html",
    ".txt" => "text/plain",
    ".css" => "text/css",
    ".jpg" => "image/jpeg",
    ".png" => "image/png"
)